version: '3'

services:
    db:
        image: postgres:12-alpine
        environment:
            POSTGRES_USER: posthog
            POSTGRES_DB: posthog
            POSTGRES_PASSWORD: posthog
        ports:
            - '5432:5432'
    clickhouse:
        # KEEP CLICKHOUSE-SERVER VERSION IN SYNC WITH
        # https://github.com/PostHog/charts-clickhouse/blob/main/charts/posthog/templates/clickhouse_instance.yaml#L88
        image: yandex/clickhouse-server:21.6.5
        ports:
            - '8123:8123'
            - '9000:9000'
            - '9440:9440'
            - '9009:9009'
        volumes:
            - ./idl:/idl
            - ../docker/clickhouse/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
            - ../docker/clickhouse/config.xml:/etc/clickhouse-server/config.xml
    test:
        build:
            context: ../
            dockerfile: dev.Dockerfile
        command: ./ee/bin/docker-ch-test
        volumes:
            - ..:/code
        environment:
            DATABASE_URL: 'postgres://posthog:posthog@db:5432/posthog'
            CLICKHOUSE_HOST: 'clickhouse'
            CLICKHOUSE_SECURE: 'false'
            CLICKHOUSE_VERIFY: 'false'
            KAFKA_URL: 'kafka://kafka'
            REDIS_URL: 'redis://redis:6379/'
            SECRET_KEY: 'alsdfjiosdajfklalsdjkf'
            DEBUG: 'true'
            PRIMARY_DB: 'clickhouse'
            TEST: 'true'
        depends_on:
            - db
        links:
            - db:db
            - clickhouse:clickhouse
