version: '3'

services:
    db:
        image: postgres:12-alpine
        environment:
            POSTGRES_USER: posthog
            POSTGRES_DB: posthog
            POSTGRES_PASSWORD: posthog
        restart: on-failure
    redis:
        image: 'redis:6.2.6-alpine'
        restart: on-failure
    clickhouse:
        # KEEP CLICKHOUSE-SERVER VERSION IN SYNC WITH
        # https://github.com/PostHog/charts-clickhouse/blob/main/charts/posthog/templates/clickhouse_instance.yaml#L88
        image: yandex/clickhouse-server:21.6.5
        depends_on:
            - kafka
            - zookeeper
        volumes:
            - ./idl:/idl
            - ../docker/clickhouse/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
            - ../docker/clickhouse/config.xml:/etc/clickhouse-server/config.xml
            - ../docker/clickhouse/users.xml:/etc/clickhouse-server/users.xml
        restart: on-failure
    zookeeper:
        image: bitnami/zookeeper:3.7.0
        restart: on-failure
        environment:
            ALLOW_ANONYMOUS_LOGIN: 'Yes'
    kafka:
        image: bitnami/kafka:2.8.1
        depends_on:
            - zookeeper
        environment:
            KAFKA_ADVERTISED_HOST_NAME: kafka
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_HEAP_OPTS: -Xmx512M -Xms512M
            KAFKA_BROKER_ID: 1000
            ALLOW_PLAINTEXT_LISTENER: 'Yes'
        restart: on-failure
    web: 
        image: posthog/posthog:latest
        command: bash -c "python manage.py migrate_clickhouse && ./bin/docker"
        environment:
            DATABASE_URL: 'postgres://posthog:posthog@db:5432/posthog'
            CLICKHOUSE_HOST: 'clickhouse'
            CLICKHOUSE_DATABASE: 'posthog'
            CLICKHOUSE_SECURE: 'false'
            CLICKHOUSE_VERIFY: 'false'
            KAFKA_URL: 'kafka://kafka'
            REDIS_URL: 'redis://redis:6379/'
            SECRET_KEY: 'alsdfjiosdajfklalsdjkf'
            DEBUG: 'true'
            PRIMARY_DB: 'clickhouse'
            PGHOST: db
            PGUSER: posthog
            PGPASSWORD: posthog
            KAFKA_ENABLED: 'true'
            KAFKA_HOSTS: 'kafka:9092'
        depends_on:
            - db
            - redis
            - clickhouse
            - kafka
        links:
            - db:db
            - redis:redis
            - clickhouse:clickhouse
            - kafka:kafka
        ports:
            - '80:8000'
        restart: on-failure