name: Docker

on:
    - pull_request

jobs:
    build:
        name: Test image build
        runs-on: ubuntu-20.04

        steps:
            - name: Checkout PR branch
              uses: actions/checkout@v2

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to DockerHub
              if: github.repository == 'PostHog/posthog'
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build
              id: docker_build
              uses: docker/build-push-action@v2
              with:
                  push: true
                  tags: posthog/posthog:testing

    saml:
        name: Test image build (without SAML dependencies)
        runs-on: ubuntu-20.04

        steps:
            - name: Checkout PR branch
              uses: actions/checkout@v2

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Build
              id: docker_build_no_saml
              uses: docker/build-push-action@v2
              with:
                  push: false
                  tags: posthog/posthog:testing-no-saml
                  build-args: |
                      saml_disabled=1
